# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Perform ABC sampling and distance calculation using the stick breaking procedure.
#'
#' Procedure:
#'
#' 1. samples from Dirichlet using [rdirdirgamma_beta_cpp()].
#' 2. computes summary statistics on datasets:
#'
#' - column-wise mean
#' - column-wise standard deviation
#'
#' or a set of column-wise quantiles
#'
#' 3. the generated dataset is invisibly is truncated to the same amount of rows as the observed dataset.
#' 4. compute the Minkowski norms of the differences between summary statistics.
#' 5. repeat `reps` times.
#'
#' ## RNG
#'
#' this function uses R's RNG seed.
#'
#' @param mtx_obs the observed data matrix
#' @param reps number of ABC samples (default: 1)
#' @param n_sample number of samples per source
#' @param m_sample number of sources
#' @param p_norm exponent of the L^p norm (can be `Inf`) (default: `2`)
#' @export
#' @return a reps*2 matrix of distances between summary statistics
#' @inheritParams get_number_summary_statistics
sample_ABC_rdirdirgamma_beta_cpp <- function(n_sample, m_sample, alpha_0, beta_0, nu_0, mtx_obs, reps, p_norm = 2, use_optimized_summary = FALSE) {
    .Call('_rdirdirgamma_sample_ABC_rdirdirgamma_beta_cpp', PACKAGE = 'rdirdirgamma', n_sample, m_sample, alpha_0, beta_0, nu_0, mtx_obs, reps, p_norm, use_optimized_summary)
}

#' Generate data that is accepted by ABC.
#'
#' @param mtx_obs observed data
#' @param n_sample hyperparameters that are used to generate data
#' @param m_sample hyperparameters that are used to generate data
#' @param alpha_0 hyperparameters that are used to generate data
#' @param beta_0 hyperparameters that are used to generate data
#' @param nu_0 hyperparameters that are used to generate data
#' @param summarize_eps ABC thresholds: as many as summary statistics
#' @param n_gen how many datasets are returned
#' @param max_iter how many iterations are tried
#' @param p_norm exponent of the L^p norm (can be `Inf`)
#' @return a (n x n_obs x p) array of generated data
#' @export
#' @inheritParams get_number_summary_statistics
generate_acceptable_data_cpp <- function(n_sample, m_sample, alpha_0, beta_0, nu_0, mtx_obs, summarize_eps, n_gen, max_iter, p_norm, use_optimized_summary) {
    .Call('_rdirdirgamma_generate_acceptable_data_cpp', PACKAGE = 'rdirdirgamma', n_sample, m_sample, alpha_0, beta_0, nu_0, mtx_obs, summarize_eps, n_gen, max_iter, p_norm, use_optimized_summary)
}

#' Compute distances between summary statistics.
#'
#' @param mtx_gen the generated data matrix; number of rows is free, it must have the same number of columns as `mtx_obs`
#' @param mtx_obs the observed data matrix; number of rows is free, it must have the same number of columns as `mtx_gen`
#' @param p_norm the power of the Minkowski distance (default: 2 = Euclidean)
#' @param use_optimized_summary if TRUE, use quantile matrix, else compute mean and sd vectors
#' @export
#' @return a vector of distances between summary statistics: as many entries as summary statistics
compute_distances_gen_obs_cpp <- function(mtx_gen, mtx_obs, p_norm = 2, use_optimized_summary = FALSE) {
    .Call('_rdirdirgamma_compute_distances_gen_obs_cpp', PACKAGE = 'rdirdirgamma', mtx_gen, mtx_obs, p_norm, use_optimized_summary)
}

#' Get the number of multivariate summary statistics.
#'
#' @param use_optimized_summary if TRUE, return the optimized summary statistics, else standard (mean, sd)
#' @export
#' @return an integer
get_number_summary_statistics <- function(use_optimized_summary) {
    .Call('_rdirdirgamma_get_number_summary_statistics', PACKAGE = 'rdirdirgamma', use_optimized_summary)
}

#' Compute optimized summary statistics.
#'
#' @export
#' @return a kxp matrix of summary statistics
#' @inheritParams get_summary_statistics_cpp
#' @inheritParams get_number_summary_statistics
get_optimized_summary_statistics_cpp <- function(mtx) {
    .Call('_rdirdirgamma_get_optimized_summary_statistics_cpp', PACKAGE = 'rdirdirgamma', mtx)
}

#' Compute standard summary statistics.
#'
#' @export
#' @return a kxp matrix of summary statistics
#' @inheritParams get_summary_statistics_cpp
#' @inheritParams get_number_summary_statistics
get_standard_summary_statistics_cpp <- function(mtx) {
    .Call('_rdirdirgamma_get_standard_summary_statistics_cpp', PACKAGE = 'rdirdirgamma', mtx)
}

#' Compute summary statistics.
#'
#' @param mtx a data matrix (nxp)
#' @inheritParams get_number_summary_statistics
#' @export
#' @return a kxp matrix of summary statistics
get_summary_statistics_cpp <- function(mtx, use_optimized_summary) {
    .Call('_rdirdirgamma_get_summary_statistics_cpp', PACKAGE = 'rdirdirgamma', mtx, use_optimized_summary)
}

#' Generate one sample from a Dirichlet distribution.
#'
#' ## RNG
#'
#' this function uses GSL's RNG seed, unaffected by R's RNG.
#'
#' @param alpha the Dirichlet hyperparameter
#' @param seed the RNG seed: if 0 (default), generate a time-based seed
#' @return a numeric vector
#' @export
rdirichlet_cpp <- function(alpha, seed = 0L) {
    .Call('_rdirdirgamma_rdirichlet_cpp', PACKAGE = 'rdirdirgamma', alpha, seed)
}

#' Generate from a Dirichlet distribution using the stick breaking definition (safer).
#'
#' ## RNG
#'
#' this function uses R's RNG seed.
#'
#' @param n how many samples to generate
#' @param alpha the Dirichlet hyperparameter, with p entries
#' @return a numeric matrix, n*p
#' @export
rdirichlet_beta_cpp <- function(n, alpha) {
    .Call('_rdirdirgamma_rdirichlet_beta_cpp', PACKAGE = 'rdirdirgamma', n, alpha)
}

#' Generate a Dirichlet-Dirichlet-Gamma population (unsafe).
#'
#' Generate samples from m sources and p parameters, n sample per source.
#' The between-source alpha hyperparameter used to generate the source parameters is mandatory.
#'
#' ## RNG
#'
#' this function uses GSL's RNG seed, unaffected by R's RNG.
#'
#' @param n number of samples per source
#' @param m number of sources
#' @param alpha_0 between-source Gamma hyperparameter, a scalar
#' @param beta_0 between-source Gamma hyperparameter, a scalar
#' @param nu_0 between-source Dirichlet hyperparameter, a numeric vector
#' @export
#' @return a matrix with n*m rows
#' @inheritParams rdirichlet_cpp
rdirdirgamma_cpp <- function(n, m, alpha_0, beta_0, nu_0, seed = 0L) {
    .Call('_rdirdirgamma_rdirdirgamma_cpp', PACKAGE = 'rdirdirgamma', n, m, alpha_0, beta_0, nu_0, seed)
}

#' Generate a Dirichlet-Dirichlet-Gamma population (safer).
#'
#' Generate samples from m sources and p parameters, n sample per source.
#' The between-source alpha hyperparameter used to generate the source parameters is mandatory.
#'
#' ## RNG
#'
#' this function uses R's RNG seed.
#'
#' @export
#' @return a matrix with n*m rows
#' @inheritParams rdirdirgamma_cpp
rdirdirgamma_beta_cpp <- function(n, m, alpha_0, beta_0, nu_0) {
    .Call('_rdirdirgamma_rdirdirgamma_beta_cpp', PACKAGE = 'rdirdirgamma', n, m, alpha_0, beta_0, nu_0)
}

#' Compute column-wise sd
#'
#' @param mtx a nxp matrix
#' @return a 1xp vector
colsd <- function(mtx) {
    .Call('_rdirdirgamma_colsd', PACKAGE = 'rdirdirgamma', mtx)
}

#' Compute column-wise kurtosis
#'
#' @param mtx a nxp matrix
#' @return a 1xp vector
colkurtosis <- function(mtx) {
    .Call('_rdirdirgamma_colkurtosis', PACKAGE = 'rdirdirgamma', mtx)
}

#' Compute column-wise skewness
#'
#' @param mtx a nxp matrix
#' @return a 1xp vector
colskewness <- function(mtx) {
    .Call('_rdirdirgamma_colskewness', PACKAGE = 'rdirdirgamma', mtx)
}

#' Compute the Minkowski norm of a vector
#'
#' Compute the Minkowski norm of a vector.
#' $p$ can range from 1 to infinity.
#'
#' @param v a vector
#' @param p exponent of the Minkowski norm (from 1 to Inf)
#' @return a double
norm_minkowski <- function(v, p = 2) {
    .Call('_rdirdirgamma_norm_minkowski', PACKAGE = 'rdirdirgamma', v, p)
}

